steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/microbiologyfarm-app/microbiology-repo/microbiology-frontend:latest',
    '-f', 'Dockerfile.frontend',
    '.'
  ]
images:
- 'us-central1-docker.pkg.dev/microbiologyfarm-app/microbiology-repo/microbiology-frontend:latest'
