FROM python:3.11-slim

WORKDIR /app

# Instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código da aplicação
COPY . .

# O comando a ser executado pelo Cloud Build
CMD ["python", "create_index_cloud.py"]
