# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY ./requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Copy the frontend app code
COPY app.py /app/app.py

# Expose the port streamlit will run on
EXPOSE 8080

# Run streamlit and make it accessible from outside the container
CMD ["streamlit", "run", "app.py", "--server.port=8080", "--server.address=0.0.0.0"]
